baseURL = "https://chugiau.ninja/"
title = "Kcg's Blog"

theme = "hugoplate"

timeZone = "Asia/Taipei"

enableInlineShortcodes = true
enableRobotsTXT = true
enableEmoji = true

paginate = 6
summaryLength = 70

languageCode = "zh-tw"
defaultContentLanguage = "zh-tw"

# googleAnalytics = ""
# disqusShortname = ""

# disable language
# example: ["fr"] for disable french language. see https://gohugo.io/content-management/multilingual/
disableLanguages = [
  "en"
]

hasCJKLanguage = true


########################## Permalinks ############################
[permalinks.page]
  "pages" = "/:slugorfilename/"

############################# Modules ############################
[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "hugo_stats.json"
    target = "assets/watching/hugo_stats.json"

############################# Build ##############################
[build]
  noJSConfigInAssets = false
  useResourceCacheWhen = 'fallback'
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/watching/hugo_stats\.json'
    target = 'style\.css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
  [[build.cachebusters]]
    source = 'assets/.*\.(js|ts|jsx|tsx)'
    target = 'js'
  [[build.cachebusters]]
    source = 'assets/.*\.(css|scss|sass)'
    target = 'css'
  [[build.cachebusters]]
    source = 'assets/.*\.(.*)$'
    target = '$1'


############################# Outputs ############################
[outputs]
  home = ["HTML", "RSS", "WebAppManifest", "SearchIndex"]

############################# Imaging ############################
[imaging]
  # See https://github.com/disintegration/imaging
  # Default JPEG or WebP quality setting. Default is 75.
  quality = 90
  resampleFilter = "Lanczos"

############################ Caches ##############################
[caches]
  [caches.images]
    dir = ":resourceDir/_gen"
    maxAge = "720h"

  [caches.assets]
    dir = ":resourceDir/_gen"
    maxAge = "720h"


############################ Markup ##############################
[markup]
  [markup.goldmark.renderer]
    unsafe = true

[markup.highlight]
  # see https://xyproto.github.io/splash/docs/all.html
  style = 'nord'

[markup.tableOfContents]
  startLevel = 2
  endLevel = 5
  ordered = true


########################### Media types ###########################
[mediaTypes]
  [mediaTypes."application/manifest+json"]
    suffixes = ["webmanifest"]


########################### Output Format ##########################
[outputFormats]
  [outputFormats.WebAppManifest]
    mediaType = "application/manifest+json"
    rel = "manifest"

  [outputFormats.SearchIndex]
    mediaType = "application/json"
    baseName = "searchindex"
    isPlainText = true
    notAlternative = true
