baseURL = "https://chugiau.ninja/"
languageCode = "zh-tw"
defaultContentLanguage = "zh-tw"
title = "KÁN Chúgiâu"
theme = "PaperMod"

timeout = "30s"
enableInlineShortcodes = true
enableRobotsTXT = true
enableEmoji = true

hasCJKLanguage = true

paginate = 5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[minify]
  disableXML = true
  minifyOutput = true

[related]
  includeNewer = true
  threshold = 80
  toLower = false
  [[related.indices]]
    name = "series"
    weight = 200
  [[related.indices]]
    name = 'keywords'
    weight = 100
  [[related.indices]]
    name = "categories"
    weight = 20
  [[related.indices]]
    name = "tags"
    weight = 50

[taxonomies]
  category = 'categories'
  tag = 'tags'

[menus]
  [[menus.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 20
  [[menus.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 30
  [[menus.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 40
  [[menus.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 50
  [[menus.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 60

[params]
  description = "A game developer's blog."
  author = "KÁN Chúgiâu"
  defaultTheme = "auto"
  disableThemeToggle = false
  showReadingTime = true
  showShareButtons = false
  showPostNavLinks = true
  showBreadCrumbs = true
  showCodeCopyButtons = true
  showWordCount = true
  showRssButtonInSectionTermList = true
  useHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = true
  hideMeta = false
  hideSummary = false
  showToc = true
  tocOpen = false
  disableHLJS = true
  images = ["img/icon.png"]
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/chugiau"
  [[params.socialIcons]]
    name = "gitlab"
    url = "https://gitlab.com/chugiau"
  [[params.socialIcons]]
    name = "email"
    url = "mailto:kan@chugiau.ninja"
  [[params.socialIcons]]
    name = "rss"
    url = "index.xml"
  [params.cover]
    hidden = false
    hiddenInList = false
    hiddenInSingle = false
  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    keys = [
      "title",
      "series",
      "categories",
      "keywords",
      "tags",
      "summary",
      "content",
    ]
  [params.assets]
    disableHLJS = true
  [params.homeInfoParams]
    title = "Hi there!"
    content = "Welcome to my blog"
  [params.profileMode]
    enabled = false
    subtitle = "No Game No Life"
    [[params.profileMode.buttons]]
      name = "Posts"
      url = "/posts"
    [[params.profileMode.buttons]]
      name = "Tags"
      url = "/tags"

[privacy]
  [privacy.vimeo]
    disable = true
    simple = true
  [privacy.twitter]
    disable = true
    enableDNT = true
    simple = true
    disableInlineCSS = true
  [privacy.instagram]
    disable = true
    simple = true
  [privacy.youtube]
    disable = true
    privacyEnhanced = true

[services]
  [services.instagram]
    disableInlineCSS = true
  [services.twitter]
    disableInlineCSS = true

[markup]
  [markup.highlight]
    #anchorLineNos = false
    #codeFences = true
    #guessSyntax = false
    #hl_lines = ''
    #lineAnchors = ''
    #lineNoStart = 1
    #lineNos = true
    #lineNumbersInTable = true
    #noClasses = true
    style = "nord"
    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
