################ English language ##################
[en]
  languageName = "En"
  languageCode = "en-us"
  contentDir = "content/english"
  weight = 2

[zh-tw]
  languageName = "正體中文"
  languageCode = "zh-tw"
  contentDir = "content/zh-tw"
  weight = 1
