#################### default parameters ################################
# favicon
favicon = "favicon.ico"
# logo
logo = "images/apple-touch-icon.png"
logo_darkmode = "images/apple-touch-icon.png"
# use `px` or `x` with logo_width, example: "100px".
# Note: logo_width is not work with .svg file
logo_width = "48px"
logo_height = "48px"
# if logo_webp set false, will not generate WEBP version of logo | default is true
logo_webp = true
# logo text will only show when logo is missing.
logo_text = "Kcg"
# navbar fixed to top
navbar_fixed = true
# theme-mode
theme_switcher = true
theme_default = "dark" # available options [light/dark/system]
# Main Sections
mainSections = ["blog"]
# contact form action
contact_form_action = "#" # contact form works with [https://airform.io/] or [https://formspree.io]
# google tag manager, see https://developers.google.com/tag-manager/
google_tag_manager = "" # example: G-XXXXXXXXXX
google_adsense = ""     # example: ca-pub-xxxxxxxxxxxxxxxx
# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>"
custom_script = ""
# copyright
# copyright = "© 2023 [Kán Chúgiâu](https://chugiau.ninja)"

# Preloader
[preloader]
  enable = false
  preloader = "" # use jpg, png, svg or gif format.

# # Navigation button
# [navigation_button]
#   enable = true
#   label = "get a quote"
#   link = "contact"

# search
[search]
  enable = true
  primary_color = "#121212"
  include_sections = ["blog"]
  show_image = true
  show_description = true
  show_tags = true
  show_categories = true


# seo meta data for OpenGraph / Twitter Card
[metadata]
  keywords = ["Blog", "Tech", "Programming", "Code"]
  description = "Kcg's Blog"
  author = "Kán Chúgiâu"
  image = "images/android-chrome-192x192.png"


# site verifications
[site_verification]
  google = ""   # Your verification code
  bing = ""     # Your verification code
  baidu = ""    # Your verification code
  facebook = "" # Your verification code
  mastodon = "" # Your verification code

# cookies
[cookies]
  enable = false
  expire_days = 60
  content = "This site uses cookies. By continuing to use this website, you agree to their use."
  button = "I Accept"

######################## sidebar widgets #########################
[widgets]
  sidebar = ["categories", "tags"]


# google map
[google_map]
  enable = false
  map_api_key = ""
  map_latitude = ""
  map_longitude = ""
  map_marker = "images/marker.png"


# Subscription
[subscription]
  enable = false
  # mailchimp subsciption
  mailchimp_form_action = "" # replace this url with yours
  mailchimp_form_name = ""
