image: registry.gitlab.com/pages/hugo:0.88.1

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
    - hugo
  except:
    - master

pages:
  script:
    - hugo --environment production
  artifacts:
    paths:
      - public
  only:
    - master
