baseURL = "https://chugiau.ninja/"
languageCode = "zh-tw"
defaultContentLanguage = "zh-tw"
title = "KÁN Chúgiâu"
theme = "PaperMod"

timeout = 30000
enableInlineShortcodes = true
enableRobotsTXT = true
enableEmoji = true

hasCJKLanguage = true

paginate = 5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[minify]
  disableXML = true
  minifyOutput = true

[related]
  includeNewer = true
  threshold = 80
  toLower = false
  [[related.indices]]
    name = "series"
    weight = 200
  [[related.indices]]
    name = 'keywords'
    weight = 100
  [[related.indices]]
    name = "categories"
    weight = 20
  [[related.indices]]
    name = "tags"
    weight = 50

[languages]
  [languages.zh-tw]
    languageName = "繁體中文"
    weight = 1

[taxonomies]
  category = 'categories'
  series = 'series'
  tag = 'tags'

[menus]
  [[menus.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 20
  [[menus.main]]
    identifier = "series"
    name = "Series"
    url = "/series/"
    weight = 25
  [[menus.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 30
  [[menus.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 40
  [[menus.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 50
  [[menus.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 60

[params]
  description = "A game developer's blog."
  author = "KÁN Chúgiâu"
  defaultTheme = "light"
  disableThemeToggle = false
  showReadingTime = true
  showShareButtons = false
  showPostNavLinks = true
  showBreadCrumbs = true
  showCodeCopyButtons = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hideMeta = false
  hideSummary = false
  showToc = true
  tocOpen = false
  [params.profileMode]
    enabled = true
    subtitle = "No Game No Life"
    [[params.profileMode.buttons]]
      name = "Posts"
      url = "/posts"
    [[params.profileMode.buttons]]
      name = "Tags"
      url = "/tags"
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/chugiau"
  [[params.socialIcons]]
    name = "email"
    url = "mailto:kan@chugiau.ninja"
  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    keys = ["title", "permalink", "summary", "content"]

[privacy]
  [privacy.vimeo]
    disable = true
    simple = true
  [privacy.twitter]
    disable = true
    enableDNT = true
    simple = true
    disableInlineCSS = true
  [privacy.insagram]
    disable = true
    simple = true
  [youtube]
    disable = true
    privacyEnhanced = true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = 'native'
    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
