name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - uses: actions/cache@v3
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      - name: Build
        uses: jakejarvis/hugo-build-action@v0.111.3
        with:
          args: --environment production

      - name: Publish
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
